export const globalsAlias: Record<string, string> = {
  vue: `Vue`,
  'vue-router': `VueRouter`,
  'element-plus': `ElementPlus`,
  '@/apis/http': `Request`,
  '@/apis/sign': `SignAPI`,
  '@/utils/date': `DateUtil`,
  '@vueuse/core': `VueUse`,
  '@/composables/useConvert': `UseConvert`,
  '@/views/good/examine/shop/components/audit-goods.vue': `auditGoodsVue`,
  '@/apis/decoration': `DecorationAPI`,
  'lodash-es': `Lodash`,
  '@/store/modules/shopInfo': `ShopInfoStore`,
  '@/apis/good': `GoodAPI`,
  '@element-plus/icons-vue': `ElementPlusIconsVue`,
  '@/components/SchemaForm.vue': `SchemaForm`,
  '@/components/chrome-tab/index.vue': `ChromeTab`,
  '@/components/ChromeTab.vue': `ChromeTabs`,
  //分页管理器
  '@/components/pageManageS/PageManage.vue': `PageManage`,
  '@/components/BetterPageManage/BetterPageManage.vue': 'PageManage',
  '@/components/PageManage.vue': `PageManageTwo`,
  //q-table
  '@/components/qszr-core/packages/q-table/QTable': `QTable`,
  '@/components/qszr-core/packages/q-table/q-table-column.vue': `QTableColumn`,
  '@/views/order/components/order-split-table/SplitTable': 'SplitTable',
  '@/views/order/components/order-split-table/split-table-column.vue': 'SplitTableColumn',
  'decimal.js': `Decimal`,
  'vue-clipboard3': `VueClipboard3`,
  '@/components/q-choose-goods-popup/q-choose-goods-popup.vue': `QChooseGoodsPopup`,
  '@/components/q-icon/q-icon.vue': `QIcon`,
  '@/utils/http': 'UtilsHttp',
  '@/utils/types': 'UtilsTypes',
  '@/components/q-choose-goods-popup': `QChooseGoodsPopupFun`,
  '@/components/q-choose-goods-popup/types': `QChooseGoodsPopupType`,
  '@/components/q-btn/q-dropdown-btn.vue': `QDropdownBtn`,
  '@/components/q-editor/q-edit.vue': 'QEditor',
  '@/components/q-upload/q-upload.vue': 'QUpload',
  '@/components/q-input-number/q-input-number.vue': `QInputNumber`,
  '@/components/remark/remark-popup.vue': 'RemarkPopup',
  '@/apis/shops': 'ShopAPI',
  // 本地缓存 s
  '@/utils/Storage': 'Storage',
  '@/libs/storage': 'storage',
  '@/store/modules/GDRegionData': 'GDRegionData',
  // 本地缓存 e
  '@/components/q-tooltip/q-tooltip.vue': 'QTooltip',
  '@/components/q-address': 'QAddressIndex',
  '@/components/q-address/q-address.vue': 'QAddress',
  'vue-draggable-next': 'VueDraggableNext',
  '@/apis/upload': 'UploadAPI',
  '@/components/q-edit/q-edit.vue': 'QEdit',
  '@/composables/usePlatformGoodStatus': 'PlatformGoodStatus',
  '@/components/q-editor/editor.vue': 'Editor',
  '@/assets/json/data.json': 'handleGetCompanyName',
  '@/components/remark/remark-flag.vue': 'RemarkFlag',
  '@/assets/image/ex_img.png': 'ExampleImg',
  '@/assets/image/supplier_to_be_audited.png': 'supplierToBeAudited',
  '@/assets/images/icon/information.png': 'information',
  '@/assets/images/icon/paymentVoucher.png': 'paymentVoucher',
  '@/views/order/orderDetails/components/remark-view.vue': 'RemarkView',
  '@/apis/afs': 'ApisAfs',
  '@/composables/stomp/StompHandler': 'StompHandler',
  '@/views/message/components/aside/Index.vue': 'MessageAside',
  '@/views/message/components/main/Index.vue': 'MessageMain',
  '@/views/message/components/types': 'MessageTypes',
  '@/composables/stomp/typs': 'StompTypes',
  '@/libs/validate': 'LibsValidate',
  '@/components/q-map/q-map.vue': 'QMap',
  '@/components/slide-captcha/SliderCaptcha.vue': 'SliderCaptcha',
  '@/components/element-plus-table-drag/drag-table.vue': 'dragTable',
  '@/components/q-mapcity/q-mapcity.vue': 'QMapcity',
  '@/utils/uuid': 'UtilsUuid',
  '@/components/q-area-choose/area-choose.vue': 'QAreaChoose',
  '@/q-plugin/index.vue': 'QPlugin',
  '@/q-plugin/cityDistribution/CityDistributionCheckbox.vue': 'CityDistributionCheckbox',
  '@/q-plugin/freight/FreightCheckBox.vue': 'FreightCheckBox',
  '@/constant': 'Constant',
  '@/views/material/selectMaterial.vue': 'selectMaterial',
  '@/views/toTopGoCar/index.vue': 'ToTopGoCar',
  '@/utils/formatRichText': 'formatRichText',
  '@/views/personalcenter/assets/integral/componets/orderTrace.vue': 'OrderTrace',
  '@/components/countdown.vue': 'Countdown',
  '@/components/teps.vue': 'Teps',
  '@/pluginPackage/seckill/components/countdown.vue': 'countdown',
  '@/apis/setting': `SettingAPI`,
  '@/views/order/platform.vue': 'PlatformComp',
  '@/components/element-plus/el-table/ElTableEmpty/index.vue': 'ElTableEmpty',
  '@/views/detail/types/index': 'DetailTypes',
  '@/assets/images/ex_img.png': 'exampleImg',
  '@/components/TitleBar/TitleBar.vue': 'TitleBar',
  '@/views/set/components/DescStep.vue': 'DescStep',
  '@/views/set/components/StepDialog.vue': 'StepDialog',
  '@/q-plugin/components/printer.vue': 'SetPinter',
  '@/q-plugin/components/printTemplate.vue': 'SetPrintTemplate',
  '@/q-plugin/components/printingTask.vue': 'SetPrintingTask',
  '@/assets/map.json': 'GD_regionData', // 高德地图数据
  '@/assets/images/delivery_key.png': 'DeliveryOfficialKey',
  '@/components/QSafeBtn/QSafeBtn.vue': 'QSafeBtn',
}

/**
 * vite.config.ts 通用配置
 * @param name 组件名称
 */
export default (name: string) => {
  const globals = { ...globalsAlias }
  for (const key in globals) {
    globals[key] = `${name}Context.${globals[key]}`
  }
  return {
    globals,
    external: Object.keys(globals),
  }
}
