export type AppPluginName =
  | 'addon-matching-treasure'
  | 'gruul-mall-addon-intraCityDistribution'
  | 'addon-full-reduction'
  | 'addon-team'
  | 'addon-shop-store'
  | 'addon-distribute'
  | 'gruul-mall-addon-platform'
  | 'addon-coupon'
  | 'addon-seckill'
  | 'addon-integral'
  | 'addon-member'
  | 'ship-cost'
  | 'addon-platform-coupon'
